apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  KAFKA_CLUSTER_USERNAME: "JRJAQNAUXI7WRRQN"
  KAFKA_CLUSTER_SECRET: "VObT2K6oH3RPbKGn9kdp9NzqmCZGTvpFvTmEiFAlbqrRksKEmqoxHWv/au+J0Fdt"
  MONGO_URI: "mongodb+srv://aminbista:nhawk4893@atlascluster.fwl80mv.mongodb.net/"
  KAFKA_CLUSTER_SERVER: "pkc-312o0.ap-southeast-1.aws.confluent.cloud:9092"