apiVersion: batch/v1
kind: Job
metadata:
  name: auth-migrate
spec:
  template:
    spec:
      containers:
        - name: auth
          image: aminbista/auth:latest
          command: ["/bin/sh","-c"]
          args: ["python manage.py migrate"]
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
      restartPolicy: Never
  backoffLimit: 5