apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-backend
        image: "<image url>"
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: auth-secret